[package]
name = "innocent_app"
version = "0.1.0"
authors = ["Jared Harper <jared.kuolt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bad_actor = { path = "../bad_actor", version = "0.1" }